apiVersion: apps/v1
kind: Deployment
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  selector:
    matchLabels:
      app: "goserver"
  replicas: 2
  template:
      metadata:
        labels:
            app: "goserver"
      spec:
        containers:
            - name: "goserver"
              image: thiagoximenes/helloworld:v5.2
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: goserver-env
              volumeMounts:
                - mountPath: /go/my-family
                  name: config
                  readOnly: true
        restartPolicy: Always
        volumes:
          - name: config
            configMap:
              name: configmap-family
              items:
                - key: members
                  path: family.txt
