apiVersion: v1
kind: Pod
metadata:
  name: "goserver"
  labels:
    app: "goserver"
spec:
  containers:
    - name: "goserver"
      image: thiagoximenes/helloworld:latest
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
