apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  ports:
      - name: goserver-service
        port: 8080
        targetPort: 80
        protocol: TCP
  type: LoadBalancer
  